### ISSUE TITLE
more input sanitation required

### ISSUE THREAD

**Issue by dan4222** [GCCempt/GCC_OpenSong_bot#104]
Placing a dash at the end of a Song line in the worship schedule causes the song validation to fail spectacularly.

Example

Songs
* The Lord is My Salvation - V1 V2 C V3 V4 C V5 C B1 B2 -

![image](https://user-images.githubusercontent.com/34949488/119208251-5d09ed80-ba6f-11eb-987d-c277592445d9.png)

**Comment by AllDayJon** [comment]
I cannot seem to reproduce this - do you know which commit main was on when this happened?

**Comment by dan4222** [comment]
unable to recreate issue by postings by any of the Dev team. Issue seems persistent whenever a worship schedule is posted by a user in Prod.

On hold till issue is seen after the 2.00 release.

**Comment by dan4222** [comment]
Issue is still occurring after v2.00 

![image](https://user-images.githubusercontent.com/34949488/121783144-134a8980-cb7b-11eb-94ee-cf4a96a0b752.png)
