### ISSUE TITLE
Main branch cleanup

### ISSUE THREAD

**Issue by AllDayJon** [GCCempt/GCC_OpenSong_bot#18]
There are a number of files that could be removed from the main branch as they are only used in testing, are temporary, or generated as part of an IDE. These could also be added to gitignore.

- [ ] .vscode directory
- [ ] __pycache__
- [ ] sample_sets
- [ ] bulletin directory
- [ ] .env
- [ ] hello-world.py
- [ ] sets directory
- [ ] songs directory
- [ ] sample_sets directory

The directories are generated on-use and shouldn't be needed in the repository. I'd suggest a test.py file be created with all the needed test cases and ability to generate sample data if needed.

**Comment by dan4222** [comment]
All of those directories besides the sample_sets directory should have already been added to the gitignore file.
The sample_sets directory and contents in there are needed as they are the templates used to create the current set.

**Comment by AllDayJon** [comment]
@dan4222  the songs, sets, and bulletin directories do not contain anything until after the bot generates the text files correct? There's nothing in there that needs to be stored inside of the VCS. The script would generate the files as needed, if there's a conflict that is caused by that, we can open a new issue to fix it. Thoughts?
