### ISSUE TITLE
Hard-coded API key

### ISSUE THREAD

**Issue by AllDayJon** [GCCempt/GCC_OpenSong_bot#19]
https://github.com/GCCempt/GCC_OpenSong_bot/blob/344746c0bc514061059ead1f2f4514de35440ad2/passagelookup.py#L7-L8

These exists in all current branches

**Comment by Infosecguy10** [comment]
Moved ESV API key to system environment variables
Added:
ESV_API_KEY
ESV_API_URL

Tested successfully
