### ISSUE TITLE
status response message should include the date that is being checked (upcoming  Sunday)

### ISSUE THREAD

**Issue by dan4222** [GCCempt/GCC_OpenSong_bot#20]
Currently, the $status command displays the "current" status of the build set process.  It shows the date / time when the command was run, but not what date it is looking for.
I think it would be useful / informative to include the "set date" in the results of the commands so the user knows which set is being processed.

**Comment by dan4222** [comment]
Completed

**Comment by Infosecguy10** [comment]
modified the monitorfiles.filechecker function to find the date of "next sunday" (relative to today) and that should be the bulletin date.
