### ISSUE TITLE
Add a check for the sermon info like the other modules (confession of sin, assurance of pardon)

### ISSUE THREAD

**Issue by dan4222** [GCCempt/GCC_OpenSong_bot#26]

**Comment by Infosecguy10** [comment]
filelist.SermonInfoFilename = sermoninfo.txt

add the following definition to filelist.py
OLDSermonInfoFilename = 'old_sermoninfo.txt'

add rename of 'sermoninfo.txt' to 'old_sermoninfo.txt' in opensong.cleanup()
os.replace(filelist.SermonInfoFilename, filelist.OldSermonInfoFilename)

update monitorfiles.filechecker() to check for the sermoninfo file:
add check if sermoninfo file exists;
