### ISSUE TITLE
Change song search to use the list of songs rather than building the URL first

### ISSUE THREAD

**Issue by dan4222** [GCCempt/GCC_OpenSong_bot#43]

**Comment by AllDayJon** [comment]
![image](https://user-images.githubusercontent.com/3322930/117521791-b2c59c80-af7d-11eb-9f58-e62e99b8d1cb.png)
Currently, the displaysong() function does the lookup by using the song name passed to it. We could add a check to search the songlist XML document for the same text, then match that text to build the song url.

**Comment by Infosecguy10** [comment]
Good idea.  Please go ahead and implement the change if you don't mind?
