### ISSUE TITLE
Change the return from the status function to an embeded discord message

### ISSUE THREAD

**Issue by dan4222** [GCCempt/GCC_OpenSong_bot#51]

**Comment by dan4222** [comment]
Should help the readability of the discord channel by preventing all the status messages from mushing together

**Comment by dan4222** [comment]
In addition to changing the status message to an embed, maybe we could change the status message to a simple one line message but with reaction emoji indicators that would actually reflect the current status of processing for the week. eg. a Red "W" that turns blue when the worship schedule has been received. A Red "S" that turns blue when the sermon info has been received. 

When processing of all elements has been completed and the set has been made and published, turn all indicators Green.

**Comment by AllDayJon** [comment]
The function that returns the status message can be found here:
https://github.com/GCCempt/GCC_OpenSong_bot/blob/847be93ad3f3fbce2bbde4898153da7dd708f984/monitorfiles.py#L15-L111

**Comment by AllDayJon** [comment]
Created a [branch for this issue](https://github.com/GCCempt/GCC_OpenSong_bot/tree/GCC_OpenSong_bot-51).
