### ISSUE TITLE
Change the command trigger from "$" to "/"

### ISSUE THREAD

**Issue by dan4222** [GCCempt/GCC_OpenSong_bot#52]
This should allow a list of possible commands to be shown when starting to type a command in discord

**Comment by AllDayJon** [comment]
> This should allow a list of possible commands to be shown when starting to type a command in discord

Slash commands were added to the official discord API on April 5th via three new routes:

`GET Guild Application Command Permissions`
`GET Application Command Permissions`
`PUT Application Command Permissions`

A `default_permission` field has also been added to the [ApplicationCommand ](https://discord.com/developers/docs/interactions/slash-commands#applicationcommand)model. This field allows you to disable commands for everyone in a guild by default, if you prefer to make some of your commands an opt-in experience.

The pythonic wrapper we use to make API calls (discord.py) has not been updated with these yet.

**Comment by evaxie236** [comment]
dunno i stAged a cHaNGE  where i replaced all the $ with / . not sure if that's what you want tho
