### ISSUE TITLE
When the set is complete put an embed message in the "read" channel with the link to the current set on the website

### ISSUE THREAD

**Issue by dan4222** [GCCempt/GCC_OpenSong_bot#57]

**Comment by evaxie236** [comment]
soooo when you make a set with the bot it would send a link to the website like the link to here or something? http://gccpraise.com/os-viewer/preview_set.php?s=2021-01-01%20GCCEM%20Sunday%20Worship

**Comment by AllDayJon** [comment]
> 
> 
> soooo when you make a set with the bot it would send a link to the website like the link to here or something? http://gccpraise.com/os-viewer/preview_set.php?s=2021-01-01%20GCCEM%20Sunday%20Worship

Yeah - that sounds right. @dan4222  is this support to be a link to the set just built, or the previous?

@evaxie236  - You can see an example of an embed here:
https://github.com/GCCempt/GCC_OpenSong_bot/blob/55e52f8b852e12c89ff007ca41c7114bdded974d/utils.py#L56-L59

You can also use sites like https://cog-creators.github.io/discord-embed-sandbox/ to make it a bit easier to visualize.

**Comment by evaxie236** [comment]
> > soooo when you make a set with the bot it would send a link to the website like the link to here or something? http://gccpraise.com/os-viewer/preview_set.php?s=2021-01-01%20GCCEM%20Sunday%20Worship
> 
> Yeah - that sounds right. @dan4222 is this support to be a link to the set just built, or the previous?
> 
> @evaxie236 - You can see an example of an embed here:
> https://github.com/GCCempt/GCC_OpenSong_bot/blob/55e52f8b852e12c89ff007ca41c7114bdded974d/utils.py#L56-L59
> 
> You can also use sites like https://cog-creators.github.io/discord-embed-sandbox/ to make it a bit easier to visualize.

yess i remember a friend found out how to make those fancy embed messages when he made a discord bot

**Comment by dan4222** [comment]
@evaxie236 yeah it would be a direct link to the set like this - http://gccpraise.com/os-viewer/publish_set.php?s=2021-01-01%20GCCEM%20Sunday%20Worship

@AllDayJon it would be to the set which was just built

**Comment by Infosecguy10** [comment]
Post this message to the read channel as an embed with a link to the set: OpenSong Set created on: 05/16/2021 23:04 PM

**Comment by dan4222** [comment]
resolved b12bae44ada38ce106cc9b9beab5b72697815c8c
