### ISSUE TITLE
Bug with Song validation on the worship schedule

### ISSUE THREAD

**Issue by dan4222** [GCCempt/GCC_OpenSong_bot#58]
On the following Worship schedule, "All Hail The Power of Jesus Name" should be "All Hail The Power **O**f Jesus Name" however the return states that all songs are valid.

5/09/21 Worship Schedule 
 
Worship Leader: Tony
Speaker: Pastor Arthur
Hymn: All Hail The Power of Jesus Name - V1 V3 V5 V6
 
Praise Team
Tony, Judy
 
Booth
Computer: Mr. Rogers
Sound: Caleb
Camera: Daniel
 
Songs
* Is He Worthy - V1 V2 C1 V3 C2 E
* Jesus Paid It All - V1 C1 V2 C1 V3 C2 B B2 C1
* Standing On The Promises - V1 V2 C V4 C V5 C

**Comment by dan4222** [comment]
It might just be because The hymn is not being checked as one of the songs and only the last 3 praise songs are being included in the check right now?

**Comment by AllDayJon** [comment]
Correct, I don't check for the hymn at all. Actually didn't know that was even there haha

**Comment by dan4222** [comment]
Before I forget, this issue prompted the discussion about possibly storing a local database of the song names for validation.
