### ISSUE TITLE
multi=part scripture passages are not correctly parsed

### ISSUE THREAD

**Issue by Infosecguy10** [GCCempt/GCC_OpenSong_bot#77]

**Comment by Infosecguy10** [comment]
On multi-part passages, the 2nd passage does not line-break at the end of the first passage.  e.g.
Input Passage= galatians 3:18; 28-29

Resulting data:
18 For if the inheritance comes by the law, it no longer comes by promise; but God gave 
it to Abraham by a promise. galatians 3:28-29 28 There is neither Jew nor Greek,

The 2nd passage should start after a line-break;
start in passagelookup.parse_passages()

**Comment by dan4222** [comment]
Observed issue when parsing Hebrews 13:22; 1:1–2:4
Hebrews 1:14 runs into Hebrews 2:1

14 Are they not all ministering spirits sent out to serve for the sake of those who are to inherit salvation?:1 Therefore we must pay much closer attention to what we have heard, lest we drift away from it.
