### ISSUE TITLE
"setNameAttrib" variable referenced before being assigned

### ISSUE THREAD

**Issue by AllDayJon** [GCCempt/GCC_OpenSong_bot#79]
https://github.com/GCCempt/GCC_OpenSong_bot/blob/847be93ad3f3fbce2bbde4898153da7dd708f984/opensong.py#L242-L247

The except clause will always reference a variable before it can be assigned.

**Comment by Infosecguy10** [comment]
fixed - removed the section of code which atttempted to clean up the "Set".  It was causing other issues for the monitorfiles.filechecker() routine which expected the Set to exist.
Issue resolved.
