### ISSUE TITLE
Remove duplicate song from website

### ISSUE THREAD

**Issue by AllDayJon** [GCCempt/GCC_OpenSong_bot#85]
Duplicate song causes a logic error when doing song validation. Currently this shouldn't cause any issue for a end-user but does create problems when using the returned "Valid Songs" list elsewhere.

[Website Song List](http://gccpraise.com/opensongv2/xml/)
![image](https://user-images.githubusercontent.com/3322930/118576606-d8f5f400-b756-11eb-90db-a697f912726d.png)

**Comment by Infosecguy10** [comment]
Complete.  Deleted "See Amid THe Winters Snow" from the website.
