### ISSUE TITLE
Song lookup at worship-schedule message  post

### ISSUE THREAD

**Issue by dan4222** [GCCempt/GCC_OpenSong_bot#9]
When The worship leader posts the worship schedule, if there is not an exact match for all songs in the message, have the bot return a message which warns the poster that the song was not found and display a list of songs which may match for them to choose one.

**Comment by AllDayJon** [comment]
@dan4222  - I can grab this issue. Let's jump on a call to discuss the testing environment whenever you're free.

**Comment by Infosecguy10** [comment]
After thinking about it, I think the validation should be done against the website?  We should use the website as the system-of-record.  This would be in line with the functioning of the  "$displaysong" command which retrieves matching songs from the website.  However, I am open to other recommendations.
